Importin the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

importing the dataset

In [2]:
dataset = pd.read_csv('TSLA.csv')
x_train = dataset[['Open', 'High', 'Low', 'Volume']].values
y_train = dataset[['Close']].values
print (x_train)

[[1.90000000e+01 2.50000000e+01 1.75400010e+01 1.87663000e+07]
 [2.57900010e+01 3.04200000e+01 2.32999990e+01 1.71871000e+07]
 [2.50000000e+01 2.59200000e+01 2.02700000e+01 8.21880000e+06]
 ...
 [6.32419983e+02 6.50880005e+02 6.18000000e+02 2.90057000e+07]
 [6.40000000e+02 6.53000000e+02 6.32520020e+02 1.57193000e+07]
 [6.73690002e+02 7.86140015e+02 6.73520020e+02 4.70650000e+07]]


Training the Multiple random forest Regression model on the Training set

In [3]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=1000, random_state=126, max_features= 6)
regressor.fit(x_train, y_train)

C:\Users\kkamo\AppData\Local\Temp\ipykernel_10456\211180486.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(x_train, y_train)


RandomForestRegressor(max_features=6, n_estimators=1000, random_state=126)

Import test dataset from alphavantage

In [4]:
import requests

# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=TSLA&&apikey=2N90AKICSZ4OMEEF'
r = requests.get(url)
daily_data = r.json()
print(daily_data)

{'Meta Data': {'1. Information': 'Daily Time Series with Splits and Dividend Events', '2. Symbol': 'TSLA', '3. Last Refreshed': '2023-03-20', '4. Output Size': 'Compact', '5. Time Zone': 'US/Eastern'}, 'Time Series (Daily)': {'2023-03-20': {'1. open': '178.08', '2. high': '186.44', '3. low': '176.35', '4. close': '183.25', '5. adjusted close': '183.25', '6. volume': '129684359', '7. dividend amount': '0.0000', '8. split coefficient': '1.0'}, '2023-03-17': {'1. open': '184.515', '2. high': '186.2199', '3. low': '177.33', '4. close': '180.13', '5. adjusted close': '180.13', '6. volume': '133197140', '7. dividend amount': '0.0000', '8. split coefficient': '1.0'}, '2023-03-16': {'1. open': '180.365', '2. high': '185.81', '3. low': '178.84', '4. close': '184.13', '5. adjusted close': '184.13', '6. volume': '121374453', '7. dividend amount': '0.0000', '8. split coefficient': '1.0'}, '2023-03-15': {'1. open': '180.8', '2. high': '182.34', '3. low': '176.03', '4. close': '180.45', '5. adjusted

convert dataset to array

In [5]:
df = pd.DataFrame(daily_data['Time Series (Daily)'])
df = df.transpose()
x_test = df[['1. open', '2. high', '3. low', '6. volume']].values
y_test = df[['4. close']].values
print (x_test)

[['178.08' '186.44' '176.35' '129684359']
 ['184.515' '186.2199' '177.33' '133197140']
 ['180.365' '185.81' '178.84' '121374453']
 ['180.8' '182.34' '176.03' '145995583']
 ['177.31' '183.8' '177.1401' '143717897']
 ['167.455' '177.35' '163.91' '167790256']
 ['175.13' '178.29' '168.44' '191488872']
 ['180.25' '185.18' '172.5124' '170023794']
 ['185.04' '186.5' '180.0' '151897763']
 ['191.38' '194.2' '186.1' '148125790']
 ['198.54' '198.6' '192.3' '128100106']
 ['194.795' '200.48' '192.88' '154193277']
 ['186.74' '193.7499' '186.01' '181979154']
 ['206.21' '207.2' '198.52' '156852790']
 ['210.59' '211.23' '203.75' '153144912']
 ['202.03' '209.42' '201.26' '161028315']
 ['196.325' '197.6695' '192.8' '142228105']
 ['203.91' '205.14' '196.33' '146359950']
 ['197.93' '201.99' '191.78' '191828457']
 ['204.99' '209.71' '197.22' '180018588']
 ['199.985' '208.44' '197.5' '213738549']
 ['210.78' '217.65' '201.84' '229586538']
 ['211.755' '214.66' '206.11' '182108581']
 ['191.94' '209.82' '189.44'

compare between the outcome and the prediction

In [6]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), (y_test.reshape(len(y_test), 1))), 1))

[[180.86521887199962 '183.25']
 [181.27057950899894 '180.13']
 [183.06645967500125 '184.13']
 [179.6187083940002 '180.45']
 [181.74071715099905 '183.26']
 [173.35445640500032 '174.48']
 [173.12188734299988 '173.44']
 [177.21424804500006 '172.92']
 [184.36143213599976 '182.0']
 [190.04035893599843 '187.71']
 [193.7053809630019 '193.81']
 [197.34553167200093 '197.79']
 [190.49280930799947 '190.9']
 [200.0579322389988 '202.77']
 [206.32134937399957 '205.71']
 [203.99414972500114 '207.63']
 [195.10028000600175 '196.88']
 [199.12111219500085 '202.07']
 [195.41204865000046 '200.86']
 [200.73333272799903 '197.37']
 [201.70433237700072 '208.31']
 [214.2429597429998 '202.04']
 [209.99452201500046 '214.24']
 [200.99994104600114 '209.25']
 [190.2608905389997 '194.64']
 [200.34323166300058 '196.89']
 [209.27238074599984 '207.32']
 [198.59106085400168 '201.29']
 [193.87547976600146 '196.81']
 [195.05187015600129 '194.76']
 [195.63596267300082 '189.98']
 [191.30191248599846 '188.27']
 [176.389358207

calculate the efficiency via r-squared rule

In [7]:
from sklearn.metrics import r2_score

r_squared = r2_score(y_test, y_pred)
print(r_squared)

0.9872107925210969


perform a grid search cross validation

In [7]:
from sklearn.model_selection import GridSearchCV

## Define hyperparameter grid

param_grid = {
    'n_estimators': [1000],
    'max_features': [6],
    'random_state': [126], 
    'max_depth': [None, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
    'min_samples_split': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
    'min_samples_leaf': [1, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
    'bootstrap': [True, False]
}

grid_search = GridSearchCV(estimator=regressor, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)
grid_search.fit(x_train, y_train)

print("Best parameters: ", grid_search.best_params_)
print("Best score: ", grid_search.best_score_)

Fitting 5 folds for each of 232320 candidates, totalling 1161600 fits
